/* Autogenerated with DRAKON Editor 1.26 */
#ifndef HELLOWORLDSCENE_H62790
#define HELLOWORLDSCENE_H62790

#include "cocos2d.h"







class HelloWorld : public cocos2d::Layer
{
public:
    // implement the "static create()" method manually
    CREATE_FUNC(HelloWorld);

public:
    static cocos2d::Scene* createScene();

    virtual bool init();

};

#endif

